typedef int (*pairptr)[2];

int keysym_tbl[][2] = {
    {SDLK_DELETE,        genv::key_delete},
    {SDLK_CAPSLOCK,      genv::key_capsl},
    {SDLK_F1,            genv::key_f1},
    {SDLK_F2,            genv::key_f2},
    {SDLK_F3,            genv::key_f3},
    {SDLK_F4,            genv::key_f4},
    {SDLK_F5,            genv::key_f5},
    {SDLK_F6,            genv::key_f6},
    {SDLK_F7,            genv::key_f7},
    {SDLK_F8,            genv::key_f8},
    {SDLK_F9,            genv::key_f9},
    {SDLK_F10,           genv::key_f10},
    {SDLK_F11,           genv::key_f11},
    {SDLK_F12,           genv::key_f12},
    {SDLK_SCROLLLOCK,    genv::key_scrl},
    {SDLK_INSERT,        genv::key_insert},
    {SDLK_HOME,          genv::key_home},
    {SDLK_PAGEUP,        genv::key_pgup},
    {SDLK_END,           genv::key_end},
    {SDLK_PAGEDOWN,      genv::key_pgdn},
    {SDLK_RIGHT,         genv::key_right},
    {SDLK_LEFT,          genv::key_left},
    {SDLK_DOWN,          genv::key_down},
    {SDLK_UP,            genv::key_up},
    {SDLK_NUMLOCKCLEAR,  genv::key_numl},
    {SDLK_F13,           genv::key_f13},
    {SDLK_F14,           genv::key_f14},
    {SDLK_F15,           genv::key_f15},
    {SDLK_MENU,          genv::key_menu},
    {SDLK_LCTRL,         genv::key_lctrl},
    {SDLK_LSHIFT,        genv::key_rshift},
    {SDLK_RCTRL,         genv::key_rctrl},
    {SDLK_RSHIFT,        genv::key_lshift},
    {SDLK_LALT,          genv::key_lalt},
    {SDLK_LGUI,          genv::key_lwin},
    {SDLK_RALT,          genv::key_ralt},
    {SDLK_RGUI,          genv::key_rwin}
};
pairptr keysym_end = keysym_tbl + sizeof(keysym_tbl)/sizeof(keysym_tbl[0]);
